version: '3.8'

services:
  database:
    build:
      context: database
    image: ghcr.io/fvilarinho/demo-database:gitops
    container_name: database
    hostname: database
    ports:
      - "3306:3306"

  backend:
    build:
      context: backend
    image: ghcr.io/fvilarinho/demo-backend:gitops
    container_name: backend
    hostname: backend
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - database-data:/var/lib/mysql
    depends_on:
      - database

  frontend:
    build:
      context: frontend
    image: ghcr.io/fvilarinho/demo-frontend:gitops
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  database-data: