name: Pipeline

on:
  push:
    branches:
      - "gitflow"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "*.yml"

jobs:
  run:
    name: CI/CD Pipeline execution
    runs-on: ubuntu-latest
    steps:
    - name: Pull project files from repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh

    - name: Packaging
      run: ./package.sh

    - name: Publishing
      env:
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh