name: Pipeline

on:
  push:
    branches:
      - "gitops"
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "*.yml"

jobs:
  run:
    name: CI/CD Pipeline execution
    runs-on: ubuntu-latest
    steps:
    - name: Pull project files from the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Kubernetes client
      run: curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"; mv kubectl.sha256 kubectl; chmod +x kubectl;

    - name: Set up the environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh

    - name: Packaging
      run: ./package.sh

    - name: Publishing
      env:
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh

    - name: Deploy
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      run: ./deploy.sh